### ISSUE TITLE
NoSuchMethodError com.googlecode.javaewah.EWAHCompressedBitmap.addWord / org.eclipse.jgit.internal.storage.file.BitSet.toEWAHCompressedBitmap

### ISSUE THREAD

**Issue by dcr26** [gitblit/gitblit#1210]
hi Guys 

Sorry I have lost the error log for this error, but I just wanted to log this in case it come up again for anyone else.

We saw this error when upgrading from v1.3 to 1.8 and found that our git ui clients were not complete pushes. 

> NoSuchMethodError com.googlecode.javaewah.EWAHCompressedBitmap.addWord 

After some debugging and experimenting , we found that upgrading to the version of JavaEWAH seemed to stop the error. 

We are running on Java SE v8, as we could were getting Invalid Runtime errors on java SE v7.

I hope this helps, and maybe you guys might want to replace the old package of JavaEWAH. 

We had v0.7.9 installed and are now using JavaEWAH-1.1.6

Hope this help someone else
